import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, KeySquare, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { CopilotConnectModal } from '@/components/domain/CopilotConnectModal';

const inputClass =
  'h-9 w-full rounded-[var(--radius-sm)] border border-border-strong bg-bg px-3 font-mono text-sm text-text outline-none focus:border-accent';

type Status = { connected: boolean; last4: string | null };

/**
 * Lets a user connect their own Claude subscription to Copilot without ever
 * opening a terminal — the gap this exists to close: before this, an
 * expired/missing Claude Code login surfaced only as a dead-end inline
 * error in the chat panel ("run `claude login`"), with no way to recover
 * short of leaving the app.
 *
 * This still isn't the app performing OAuth or touching Claude.ai
 * credentials — that's against Anthropic's terms for third-party apps, and
 * is why Copilot shells out to the real `claude` CLI in the first place
 * instead of calling Anthropic's API directly. What ends up connected is a
 * token generated by Anthropic's own `claude setup-token` command, scoped
 * to inference only, tied to the user's own subscription — the primary
 * "Connect with Claude" flow (CopilotConnectModal) runs that command
 * itself, inside a real pseudo-terminal, so the user never has to; pasting
 * a token generated in an actual terminal is kept as a manual fallback for
 * when that automated flow doesn't work.
 */
export default function Copilot() {
  const [status, setStatus] = useState<Status | null>(null);
  const [statusError, setStatusError] = useState(false);
  const [connectOpen, setConnectOpen] = useState(false);
  const [token, setToken] = useState('');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [justConnected, setJustConnected] = useState(false);
  const [showManual, setShowManual] = useState(false);
  const justConnectedTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(
    null,
  );

  useEffect(() => {
    let cancelled = false;
    async function loadStatus() {
      try {
        const s = await window.electron.copilot.auth.status();
        if (!cancelled) setStatus(s);
      } catch {
        // Fail open toward "not connected" rather than leaving `status`
        // null forever — previously an unhandled rejection here (however
        // unlikely) left this whole page permanently blank, with neither
        // the connected card nor the connect button ever rendering.
        if (!cancelled) {
          setStatusError(true);
          setStatus({ connected: false, last4: null });
        }
      }
    }
    loadStatus();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(
    () => () => {
      if (justConnectedTimeoutRef.current) {
        clearTimeout(justConnectedTimeoutRef.current);
      }
    },
    [],
  );

  function handleConnected(last4: string) {
    setStatus({ connected: true, last4 });
    setJustConnected(true);
    if (justConnectedTimeoutRef.current) {
      clearTimeout(justConnectedTimeoutRef.current);
    }
    justConnectedTimeoutRef.current = setTimeout(
      () => setJustConnected(false),
      2500,
    );
  }

  async function handleManualConnect() {
    if (!token.trim() || saving) return;
    setSaving(true);
    setError(null);
    try {
      const result = await window.electron.copilot.auth.save(token.trim());
      if (!result.ok) {
        setError(result.message);
        return;
      }
      setToken('');
      setShowManual(false);
      handleConnected(result.last4);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Couldn't save the token — try again.",
      );
    } finally {
      setSaving(false);
    }
  }

  async function handleDisconnect() {
    await window.electron.copilot.auth.clear();
    setStatus({ connected: false, last4: null });
  }

  return (
    <div className="max-w-lg">
      <h2 className="mb-1 font-display text-lg font-medium text-text">
        Copilot
      </h2>
      <p className="mb-6 text-sm text-text-secondary">
        Connect your own Claude subscription so Copilot keeps working without
        needing a terminal every time your login lapses.
      </p>

      {statusError && (
        <Badge tone="danger" outline className="mb-6">
          Couldn&apos;t check your connection status — you can still try
          connecting below.
        </Badge>
      )}

      {status?.connected && (
        <div className="mb-6 flex items-center justify-between gap-3 rounded-[var(--radius-lg)] border border-border bg-surface p-3.5">
          <div className="flex items-center gap-3">
            <span className="flex size-9 shrink-0 items-center justify-center rounded-[var(--radius-sm)] bg-surface-2 text-text-secondary">
              <KeySquare size={16} />
            </span>
            <div>
              <p className="text-sm text-text">Claude subscription connected</p>
              <p className="font-mono text-xs text-text-muted">
                •••• {status.last4}
              </p>
            </div>
          </div>
          <Button variant="ghost" size="sm" onClick={handleDisconnect}>
            Disconnect
          </Button>
        </div>
      )}

      {justConnected && (
        <div className="mb-6 flex items-center gap-2 text-sm text-success">
          <CheckCircle2 size={15} />
          Connected — Copilot will use this from now on.
        </div>
      )}

      {status && !status.connected && (
        <div className="mb-8 flex flex-col gap-4">
          <div>
            <Button
              variant="primary"
              onClick={() => setConnectOpen(true)}
              className="w-full"
            >
              <Sparkles size={15} />
              Connect with Claude
            </Button>
            <p className="mt-2 text-xs text-text-muted">
              Opens your browser to sign in with Anthropic. Nothing to copy or
              paste.
            </p>
          </div>

          <button
            type="button"
            onClick={() => setShowManual((v) => !v)}
            className="cursor-pointer self-start text-xs text-text-muted underline underline-offset-2"
          >
            {showManual
              ? 'Hide manual option'
              : 'Having trouble? Paste a token manually'}
          </button>

          {showManual && (
            <div className="flex flex-col gap-3 rounded-[var(--radius)] border border-dashed border-border-strong bg-surface-2 p-3.5">
              <p className="text-xs text-text-muted">
                Run{' '}
                <code className="rounded bg-surface px-1.5 py-0.5 font-mono text-[11px] text-text">
                  claude setup-token
                </code>{' '}
                in a terminal — this opens your browser to sign in and prints a
                token. Copy that token and paste it below.
              </p>
              <div>
                <label
                  className="mb-1.5 block text-sm font-medium text-text"
                  htmlFor="claude-token"
                >
                  Subscription token
                </label>
                <input
                  id="claude-token"
                  type="password"
                  className={inputClass}
                  value={token}
                  onChange={(e) => {
                    setToken(e.target.value);
                    setError(null);
                  }}
                  placeholder="sk-ant-oat..."
                  autoComplete="off"
                  spellCheck={false}
                />
              </div>
              {error && (
                <Badge tone="danger" outline>
                  {error}
                </Badge>
              )}
              <div>
                <Button
                  variant="primary"
                  size="sm"
                  disabled={!token.trim() || saving}
                  onClick={handleManualConnect}
                >
                  {saving ? 'Validating…' : 'Connect'}
                </Button>
              </div>
            </div>
          )}
        </div>
      )}

      <CopilotConnectModal
        open={connectOpen}
        onClose={() => setConnectOpen(false)}
        onConnected={handleConnected}
      />
    </div>
  );
}
