/**
 * The comment composer's emoji picker data.
 *
 * A curated common set, not the full Unicode emoji database Jira's own
 * picker offers (thousands of entries, skin-tone variants, categories) --
 * shipping that is a real, separate undertaking (a data file, a virtualized
 * grid, category tabs) with little payoff over a well-chosen ~90 for a
 * comment box. `name` is what the picker's search box matches against, and
 * what an inserted emoji has no other record of once it's just a character
 * in the draft.
 */
export interface JiraCommentEmoji {
  char: string;
  name: string;
}

export const JIRA_COMMENT_EMOJI: JiraCommentEmoji[] = [
  { char: '😀', name: 'grinning' },
  { char: '😃', name: 'smiley' },
  { char: '😄', name: 'smile' },
  { char: '😁', name: 'grin' },
  { char: '😆', name: 'laughing' },
  { char: '😅', name: 'sweat smile' },
  { char: '🤣', name: 'rofl rolling on the floor laughing' },
  { char: '😂', name: 'joy tears of joy' },
  { char: '🙂', name: 'slightly smiling' },
  { char: '🙃', name: 'upside down' },
  { char: '😉', name: 'wink' },
  { char: '😊', name: 'blush smiling' },
  { char: '😇', name: 'innocent halo' },
  { char: '🥰', name: 'smiling hearts' },
  { char: '😍', name: 'heart eyes' },
  { char: '🤩', name: 'star struck' },
  { char: '😘', name: 'kiss' },
  { char: '😋', name: 'yum' },
  { char: '😛', name: 'tongue' },
  { char: '😜', name: 'wink tongue' },
  { char: '🤪', name: 'zany crazy' },
  { char: '🤔', name: 'thinking' },
  { char: '🤨', name: 'raised eyebrow suspicious' },
  { char: '😐', name: 'neutral' },
  { char: '😑', name: 'expressionless' },
  { char: '🙄', name: 'eye roll' },
  { char: '😏', name: 'smirk' },
  { char: '😬', name: 'grimace awkward' },
  { char: '🤐', name: 'zipper mouth quiet' },
  { char: '😴', name: 'sleeping' },
  { char: '😌', name: 'relieved' },
  { char: '😔', name: 'pensive sad' },
  { char: '😪', name: 'sleepy tired' },
  { char: '🤤', name: 'drooling' },
  { char: '😷', name: 'mask sick' },
  { char: '🤒', name: 'thermometer sick' },
  { char: '🤕', name: 'bandage hurt' },
  { char: '🥵', name: 'hot' },
  { char: '🥶', name: 'cold' },
  { char: '😵', name: 'dizzy' },
  { char: '🤯', name: 'exploding head mind blown' },
  { char: '😎', name: 'sunglasses cool' },
  { char: '🥳', name: 'party celebrate' },
  { char: '😕', name: 'confused' },
  { char: '😟', name: 'worried' },
  { char: '🙁', name: 'frown' },
  { char: '😮', name: 'open mouth surprised' },
  { char: '😯', name: 'hushed' },
  { char: '😲', name: 'astonished shocked' },
  { char: '😳', name: 'flushed' },
  { char: '🥺', name: 'pleading puppy eyes' },
  { char: '😢', name: 'cry sad' },
  { char: '😭', name: 'sob crying' },
  { char: '😱', name: 'scream fear' },
  { char: '😖', name: 'confounded' },
  { char: '😣', name: 'persevere' },
  { char: '😞', name: 'disappointed' },
  { char: '😓', name: 'sweat stressed' },
  { char: '😩', name: 'weary exhausted' },
  { char: '😫', name: 'tired' },
  { char: '😤', name: 'triumph huff' },
  { char: '😡', name: 'rage angry' },
  { char: '😠', name: 'angry' },
  { char: '🤬', name: 'cursing swearing' },
  { char: '👍', name: 'thumbs up approve' },
  { char: '👎', name: 'thumbs down' },
  { char: '👏', name: 'clap applause' },
  { char: '🙌', name: 'raised hands celebrate' },
  { char: '🙏', name: 'pray thanks please' },
  { char: '🤝', name: 'handshake deal' },
  { char: '💪', name: 'muscle strong' },
  { char: '👋', name: 'wave hello bye' },
  { char: '✌️', name: 'peace victory' },
  { char: '🤞', name: 'fingers crossed hope' },
  { char: '👀', name: 'eyes looking' },
  { char: '🔥', name: 'fire lit' },
  { char: '🎉', name: 'party popper celebrate' },
  { char: '🎊', name: 'confetti' },
  { char: '✅', name: 'check done complete' },
  { char: '❌', name: 'cross x wrong no' },
  { char: '⚠️', name: 'warning caution' },
  { char: '🚀', name: 'rocket ship it launch' },
  { char: '🐛', name: 'bug' },
  { char: '🔧', name: 'wrench fix' },
  { char: '⏰', name: 'alarm clock time' },
  { char: '📌', name: 'pin important' },
  { char: '💡', name: 'lightbulb idea' },
  { char: '❤️', name: 'heart love' },
  { char: '💯', name: 'hundred perfect' },
  { char: '⭐', name: 'star favorite' },
  { char: '☕', name: 'coffee break' },
  { char: '🎯', name: 'target bullseye goal' },
];
