import type { AgentSession } from './types';

// Fake seed data for the flag-gated agent-sessions mock frontend — not
// fetched from waypoint-server. "Ethan" matches the agent identity already
// used elsewhere in the app's own seed data (activity feed, comments).
export const MOCK_SESSIONS: AgentSession[] = [
  {
    id: 'session-1',
    workItemId: 'wi-3',
    workItemIdentifier: 'LAUNCH-3',
    workItemTitle: 'Responsive nav breaks on iPad landscape',
    projectId: 'proj-launch',
    projectName: 'Product Launch',
    agentId: 'agent-ethan',
    agentName: 'Ethan',
    agentAvatarColor: '#2f6fa8',
    intent: 'full-coding',
    status: 'running',
    createdAt: '2026-08-22T09:12:00Z',
    updatedAt: '2026-08-22T09:41:00Z',
    unread: true,
    messages: [
      {
        id: 'm1',
        role: 'user',
        text: 'Start working on this bug with this repository.',
        createdAt: '2026-08-22T09:12:00Z',
      },
      {
        id: 'm2',
        role: 'agent',
        text: "On it. Cloning into a worktree off your local waypoint-frontend checkout and reproducing the iPad-landscape breakpoint first.",
        createdAt: '2026-08-22T09:12:20Z',
      },
      {
        id: 'm3',
        role: 'agent',
        text: 'Reproduced — the nav flex container is missing a min-width guard at 1024×768, same root cause Lena flagged in the comments. Working on a fix now.',
        createdAt: '2026-08-22T09:24:00Z',
      },
      {
        id: 'm4',
        role: 'agent',
        text: 'Fix is in, running the existing Playwright regression test for tablet nav (LAUNCH-14) against it now before opening a PR.',
        createdAt: '2026-08-22T09:41:00Z',
      },
    ],
  },
  {
    id: 'session-2',
    workItemId: 'wi-9',
    workItemIdentifier: 'LAUNCH-9',
    workItemTitle: 'Rollback script fails silently on partial deploy',
    projectId: 'proj-launch',
    projectName: 'Product Launch',
    agentId: 'agent-ethan',
    agentName: 'Ethan',
    agentAvatarColor: '#2f6fa8',
    intent: 'rca',
    status: 'needs-review',
    createdAt: '2026-08-22T08:02:00Z',
    updatedAt: '2026-08-22T08:29:00Z',
    unread: true,
    messages: [
      {
        id: 'm1',
        role: 'user',
        text: 'Research and give RCA.',
        createdAt: '2026-08-22T08:02:00Z',
      },
      {
        id: 'm2',
        role: 'agent',
        text: "Found it. rollback.sh exits 0 even when the partial-deploy guard trips, because the guard's early return happens inside a subshell — the parent script never sees the failure. Three other scripts in infra/ share the same pattern.",
        createdAt: '2026-08-22T08:29:00Z',
      },
    ],
  },
  {
    id: 'session-3',
    workItemId: 'wi-7',
    workItemIdentifier: 'LAUNCH-7',
    workItemTitle: 'Set up staging → production promotion pipeline',
    projectId: 'proj-launch',
    projectName: 'Product Launch',
    agentId: 'agent-ethan',
    agentName: 'Ethan',
    agentAvatarColor: '#2f6fa8',
    intent: 'full-coding',
    status: 'blocked',
    createdAt: '2026-08-21T15:40:00Z',
    updatedAt: '2026-08-21T16:05:00Z',
    unread: true,
    messages: [
      {
        id: 'm1',
        role: 'user',
        text: 'Start working on this bug with this repository.',
        createdAt: '2026-08-21T15:40:00Z',
      },
      {
        id: 'm2',
        role: 'agent',
        text: 'The promotion pipeline needs a production deploy key to finish wiring the last step, and I don’t have one scoped to write. Waiting on you before I go further — autonomy is set to "ask before PR" for this one.',
        createdAt: '2026-08-21T16:05:00Z',
      },
    ],
  },
  {
    id: 'session-4',
    workItemId: 'wi-8',
    workItemIdentifier: 'LAUNCH-8',
    workItemTitle: 'Add automated changelog generation from PR titles',
    projectId: 'proj-launch',
    projectName: 'Product Launch',
    agentId: 'agent-ethan',
    agentName: 'Ethan',
    agentAvatarColor: '#2f6fa8',
    intent: 'comment',
    status: 'done',
    createdAt: '2026-08-21T11:10:00Z',
    updatedAt: '2026-08-21T11:12:00Z',
    unread: false,
    messages: [
      {
        id: 'm1',
        role: 'user',
        text: 'Comment on the ticket — let Sam know where this stands.',
        createdAt: '2026-08-21T11:10:00Z',
      },
      {
        id: 'm2',
        role: 'agent',
        text: 'Posted as you: "Hi, this is Ethan — Amaan’s agent — commenting on his behalf: this is queued behind the release-week freeze, picking back up Monday."',
        createdAt: '2026-08-21T11:12:00Z',
      },
    ],
  },
  {
    id: 'session-5',
    workItemId: 'wi-12',
    workItemIdentifier: 'LAUNCH-12',
    workItemTitle: 'Spike: server-sent events for live activity feed',
    projectId: 'proj-launch',
    projectName: 'Product Launch',
    agentId: 'agent-ethan',
    agentName: 'Ethan',
    agentAvatarColor: '#2f6fa8',
    intent: 'follow-up',
    status: 'failed',
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-08-20T14:03:00Z',
    unread: true,
    messages: [
      {
        id: 'm1',
        role: 'user',
        text: 'Follow up on the ticket.',
        createdAt: '2026-08-20T14:00:00Z',
      },
      {
        id: 'm2',
        role: 'agent',
        text: "Couldn't reach the local checkout for Product Launch to check the branch status — the mapped folder no longer exists on disk. Repoint it from Sessions → New session, or from the project's local setup.",
        createdAt: '2026-08-20T14:03:00Z',
      },
    ],
  },
  {
    id: 'session-6',
    workItemId: 'wi-10',
    workItemIdentifier: 'LAUNCH-10',
    workItemTitle: 'Evaluate self-serve trial vs. waitlist-only launch',
    projectId: 'proj-launch',
    projectName: 'Product Launch',
    agentId: 'agent-ethan',
    agentName: 'Ethan',
    agentAvatarColor: '#2f6fa8',
    intent: 'custom',
    customInstruction: 'Pull the last 3 weeks of signup numbers from the analytics page and summarize the tradeoff in a comment.',
    status: 'queued',
    createdAt: '2026-08-22T09:58:00Z',
    updatedAt: '2026-08-22T09:58:00Z',
    unread: true,
    messages: [
      {
        id: 'm1',
        role: 'user',
        text: 'Pull the last 3 weeks of signup numbers from the analytics page and summarize the tradeoff in a comment.',
        createdAt: '2026-08-22T09:58:00Z',
      },
    ],
  },
];
